### ISSUE TITLE
Generate PyPi Release Pipeline

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#18]
Similarly to [django-simple-bulma](https://github.com/python-discord/django-simple-bulma) we'll want a pipeline set up for automating releases to PyPi

**Comment by sco1** [comment]
Seems like someone has [worked with PyPA](https://discuss.python.org/t/official-github-action-for-publishing-to-pypi/1061/58) and created a GH action for releasing to PyPI: https://github.com/pypa/gh-action-pypi-publish

Sounds like a fun thing to try out

**Comment by sco1** [comment]
Something like the following seems to work fine with https://test.pypi.org/

```yml
name: PyPI publish

on: [create]

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Build Package
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python3 -m pip install --user --upgrade setuptools wheel
        python3 setup.py sdist bdist_wheel
      
    - name: Publish package
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token }}
        repository_url: https://test.pypi.org/legacy/
```

**Comment by sco1** [comment]
A couple minor things to do and this should be good to formally try out:

- [ ] Pin the release action to a tagged release rather than `master` (alpha was released a few hours prior to this comment)
- [ ] Trigger on a release creation rather than a tag. In addition to this being a bit cleaner code-wise, it should be a more reliable method

**Comment by sco1** [comment]
I've created a new draft based on some input from @scragly 

```yml
name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    name: Build dist & publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install build dependencies & build
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        python setup.py sdist bdist_wheel
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token }}
```

GH won't let me push to the dev branch so will just add to master after a lookover.

I tested it out on a fork, sending to the test PyPI: https://test.pypi.org/project/flake8-annotations-test/
