### ISSUE TITLE
Inadequate pre-commit linting configuration

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#26]
This repository’s flake8 pre-commit configuration currently utilizes the latest PyPi version of flake8-annotations when building its linting environment rather than the current state of the local repo. This can potentially lead to a result that conflicts with both a manual flake8 invocation and the linting CI pipeline, which utilize the current state of the repo to lint itself.

My research into method(s) to resolve this hasn’t been fruitful. Perhaps linting ourselves is an antipattern or I’m just bad at finding things on the internet, but if there’s no way to solve this then I’m inclined to remove pre-commit completely rather than have this conflict.

Would love to have some opinions and/or leads on this!

**Comment by MarkKoz** [comment]
I can look into this. However, perhaps linting with the "stable" version is better anyway?

**Comment by sco1** [comment]
One problem with that is if we’re fixing a bug then we’re linting with the buggy version instead of the fixed version.

**Comment by MarkKoz** [comment]
True, but that'd only be a problem if the code required to fix the bug triggered the bug itself.

**Comment by MarkKoz** [comment]
It can be done with a local repo. This runs flake8 in the project's venv. However, pre-commit will still create its own venv and I don't think that is avoidable.

```yaml
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8.
        entry: pipenv run lint
        language: python
        types: [python]
        require_serial: true
```
